package la.tiendita;

import src.Factura;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dieez
 */
public class Cierre extends javax.swing.JFrame {

    /**
     * Creates new form Cierre
     */
    public Cierre() {
        initComponents();
        //Coloca la Aplicacion al centro de la pantalla
        this.setLocationRelativeTo(null);
        
        //Cargar datos de arrayLists en la JTable
        DefaultTableModel modelEfectivo = new DefaultTableModel();
        modelEfectivo.setColumnIdentifiers(new String[] {"Nombre del Producto", 
            "Cantidad", "Precio Individual", "Nombre del cliente", "Nit", 
            "Total a pagar"});
        DefaultTableModel modelCheque = new DefaultTableModel();
        modelCheque.setColumnIdentifiers(new String[] {"Nombre del Producto", 
            "Cantidad", "Precio Individual", "Nombre del cliente", "Nit", 
            "Total a pagar"});
        DefaultTableModel modelCredito = new DefaultTableModel();
        modelCredito.setColumnIdentifiers(new String[] {"Nombre del Producto", 
            "Cantidad", "Precio Individual", "Nombre del cliente", "Nit", 
            "Total a pagar"});
        jTableEfectivo.setModel(modelEfectivo);
        jTableCheque.setModel(modelCheque);
        jTableCredito.setModel(modelCredito);
        
        // Llenar la JTable (TableModel) con la data de; ArrayList facturaEfectivo
        for (Factura f : Pago.facturaEfectivo)
        {
            modelEfectivo.addRow(new String[] {f.getNombreProducto(), 
            Integer.toString(f.getCantidad()), Float.toString(f.getPrecioIndividual()),
            f.getNombreCliente(), f.getNit(),Float.toString(f.getTotalVenta())});
        }
        
        // Llenar la JTable (TableModel) con la data de; ArrayList facturaCheque
        for (Factura f : Pago.facturaCheque)
        {
            modelCheque.addRow(new String[] {f.getNombreProducto(), 
            Integer.toString(f.getCantidad()), Float.toString(f.getPrecioIndividual()),
            f.getNombreCliente(), f.getNit(),Float.toString(f.getTotalVenta())});
        }
        
        // Llenar la JTable (TableModel) con la data de; ArrayList facturaCredito
        for (Factura f : Pago.facturaCredito)
        {
            modelCredito.addRow(new String[] {f.getNombreProducto(), 
            Integer.toString(f.getCantidad()), Float.toString(f.getPrecioIndividual()),
            f.getNombreCliente(), f.getNit(),Float.toString(f.getTotalVenta())});
        }
        
        double dinero = 0;
        
        for (int i = 0; i < jTableEfectivo.getRowCount(); i++) {
                dinero += Double.parseDouble(jTableEfectivo.getValueAt(i, 5).toString());
            }
        
        for (int i = 0; i < jTableCheque.getRowCount(); i++) {
                dinero += Double.parseDouble(jTableCheque.getValueAt(i, 5).toString());
            }
        
        txtDinero.setText(String.valueOf(dinero));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        txtTabla = new javax.swing.JScrollPane();
        jTableEfectivo = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCheque = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCredito = new javax.swing.JTable();
        txtDinero = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel8.setText("Cierre de caja");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Total a depositar");

        lblTotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTotal.setText("Q.");

        jTableEfectivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        txtTabla.setViewportView(jTableEfectivo);

        jTabbedPane1.addTab("Efectivo", txtTabla);

        jTableCheque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCheque);

        jTabbedPane1.addTab("Cheque", jScrollPane1);

        jTableCredito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCredito);

        jTabbedPane1.addTab("Credito", jScrollPane2);

        txtDinero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDinero.setText("\"Aca va el Dinero\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDinero)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cierre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cierre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cierre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cierre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cierre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCheque;
    private javax.swing.JTable jTableCredito;
    private javax.swing.JTable jTableEfectivo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel txtDinero;
    private javax.swing.JScrollPane txtTabla;
    // End of variables declaration//GEN-END:variables
}
